version: '3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: >
      proxy-dns
      --address 0.0.0.0
      --port 5053
      --upstream https://1.1.1.1/dns-query
      --upstream https://1.0.0.1/dns-query
    expose:
      - "5053"
    networks:
      - pihole_net
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: Europe/Stockholm
      DNS1: cloudflared#5053
      DNS2: no
      FTLCONF_dns_listeningMode: all
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "8443:443" # custom HTTPS port
    networks:
      - pihole_net
    restart: unless-stopped

networks:
  pihole_net:
    driver: bridge
